config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  resources :games do
    resources :rounds
  end
  root 'games#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :rounds
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :round
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :game

  has_many :questions

  after_create :build_questions

  def build_questions
    (0..5).to_a.each do |x_coord|
      [100, 200, 300, 400, 500].each_with_index do |value, y_coord|
        questions.create(x_coord: x_coord, y_coord: y_coord, value: value)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.rounds.each {|round| round.destroy}
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title, :author)
    end
end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout "hello_world"

  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: [:show, :edit, :update]
  # GET /rounds/1
  # GET /rounds/1.json
  def show
    round = Round.find(params["id"])
    @round_props = { questions: round.questions.all }
  end

  # GET /rounds/new
  def new
    @game = Game.find(params["game_id"])
    @round = @game.rounds.build
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @game = Game.find(params["game_id"])
    @round = @game.rounds.new(round_params)

    respond_to do |format|
      if @round.save
        format.html { redirect_to @game, notice: 'Round was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to @round, notice: 'Round was successfully updated.' }
        format.json { render :show, status: :ok, location: @round }
      else
        format.html { render :edit }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @round = Round.find(params["id"])
    @game = @round.game
    @round.destroy
    respond_to do |format|
      format.html { redirect_to game_url(@game.id), notice: 'Round was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = Round.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_params
      params.require(:round).permit(:title, :game_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/games/_form.html.slim
= form_for @game do |f|
  - if @game.errors.any?
    #error_explanation
      h2 = "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
      ul
        - @game.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :author
    = f.text_field :author
  .actions = f.submit

app/views/games/edit.html.slim
h1 Editing game

== render 'form'

= link_to 'Show', @game
'  |
= link_to 'Back', games_path

app/views/games/index.html.slim
h1 Listing games

table
  thead
    tr
      th Title
      th Author
      th
      th
      th

  tbody
    - @games.each do |game|
      tr
        td = game.title
        td = game.author
        td = link_to 'Show', game
        td = link_to 'Edit', edit_game_path(game)
        td = link_to 'Destroy', game, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Game', new_game_path

app/views/games/new.html.slim
h1 New game

== render 'form'

= link_to 'Back', games_path

app/views/games/show.html.slim
p#notice = notice

p
  strong> Title:
  = @game.title
p
  strong> Author:
  = @game.author

= link_to 'Back', games_path

h1 Rounds

table
  thead
    tr
      th Title
      th
      th
      th

  tbody
    - @game.rounds.each do |round|
      tr
        td = round.title
        td = link_to 'Play', game_round_path(@game, round)
        td = link_to 'Edit', edit_game_round_path(@game, round)
        td = link_to 'Destroy', game_round_path(@game, round), data: {confirm: 'Are you sure?'}, method: :delete

br
= link_to 'New Round', new_game_round_path(game_id: @game.id)

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jeopardy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rounds/_form.html.slim
= form_for [@game, @round] do |f|
  - if @round.errors.any?
    #error_explanation
      h2 = "#{pluralize(@round.errors.count, "error")} prohibited this round from being saved:"
      ul
        - @round.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .actions = f.submit

app/views/rounds/edit.html.slim
h1 Editing round

== render 'form'

= link_to 'Show', @round
'  |
/ = link_to 'Back', rounds_path

app/views/rounds/new.html.slim
h1 New round
== render 'form'

= link_to 'Back', game_path(@game.id)

app/views/rounds/show.html.slim
= react_component("Round", props: @round_props, prerender: false)